name: Manual Promote Develop to Main

on:
  workflow_dispatch: # Ejecución manual del flujo de trabajo
    inputs:
      reason:
        description: ' Version 1.0.1'
        required: true
        default: 'Despliegue manual'

jobs:
  promote:
    runs-on: ubuntu-latest
    # Añadimos esta sección de variables de entorno
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Git config
        run: |
          git config --global user.name "release-manager"
          git config --global user.email "release-manager@users.noreply.github.com"

      - name: Merge develop into main
        run: |
          git checkout main
          git pull origin main
          # Combinamos develop y usamos el input del usuario para el mensaje de commit
          git merge origin/develop --no-ff -m "Manual Release: ${{ github.event.inputs.reason }}"
          git push origin main
